// <auto-generated />
using System;
using Atlas.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atlas.Persistence.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    partial class AtlasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atlas.Domain.Entities.AzureConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsEnabled")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AzureConnections", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AzureSyncState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AzureConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("LastRunStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastSuccessfulChangedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastSuccessfulWorkItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AzureConnectionId")
                        .IsUnique();

                    b.ToTable("AzureSyncStates", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AzureUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descriptor")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<string>("UniqueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UniqueName")
                        .IsUnique();

                    b.ToTable("AzureUsers", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AzureUserMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AzureUniqueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LinkedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AzureUniqueName")
                        .IsUnique();

                    b.HasIndex("TeamMemberId");

                    b.ToTable("AzureUserMappings", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AzureWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AssignedToUniqueName")
                        .HasColumnType("text");

                    b.Property<Guid>("AzureConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IterationPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rev")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkItemType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AzureConnectionId", "WorkItemId")
                        .IsUnique();

                    b.ToTable("AzureWorkItems", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AzureWorkItemLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AzureWorkItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LinkedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AzureWorkItemId")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("AzureWorkItemLinks", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Growth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FocusAreasMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId")
                        .IsUnique();

                    b.ToTable("GrowthPlans", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.GrowthFeedbackTheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GrowthId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObservedSinceLabel")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrowthId");

                    b.ToTable("GrowthFeedbackThemes", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.GrowthGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GrowthId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.Property<int?>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuccessCriteria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrowthId");

                    b.ToTable("GrowthGoals", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.GrowthGoalAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("Evidence")
                        .HasColumnType("text");

                    b.Property<Guid>("GrowthGoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrowthGoalId");

                    b.ToTable("GrowthGoalActions", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.GrowthGoalCheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("GrowthGoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Signal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GrowthGoalId", "Date");

                    b.ToTable("GrowthGoalCheckIns", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.GrowthSkillInProgress", b =>
                {
                    b.Property<Guid>("GrowthId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("GrowthId", "Value");

                    b.HasIndex("GrowthId", "SortOrder")
                        .IsUnique();

                    b.ToTable("GrowthSkillsInProgress", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ProductOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductOwners", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Health")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductOwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProductOwnerId");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ProjectLinkItem", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("ProjectId", "Label", "Url");

                    b.ToTable("ProjectLinks", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ProjectTag", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("ProjectId", "Value");

                    b.ToTable("ProjectTags", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ProjectTeamMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "TeamMemberId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("ProjectTeamMembers", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Risk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Risks", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.RiskHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RiskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RiskId");

                    b.ToTable("RiskHistoryEntries", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.RiskTeamMember", b =>
                {
                    b.Property<Guid>("RiskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.HasKey("RiskId", "TeamMemberId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("RiskTeamMembers", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Settings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AzureDevOpsBaseUrl")
                        .HasColumnType("text");

                    b.Property<string>("DefaultAiManualOnly")
                        .IsRequired()
                        .HasColumnType("character varying(5)");

                    b.Property<int>("StaleDays")
                        .HasColumnType("integer");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockerTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DependentTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BlockerTaskId");

                    b.HasIndex("DependentTaskId", "BlockerTaskId")
                        .IsUnique();

                    b.ToTable("TaskDependencies", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActualDurationText")
                        .HasColumnType("text");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("EstimateConfidence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EstimatedDurationText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastTouchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RiskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RiskId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentFocus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusDot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TeamMemberRisk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FirstNoticedDate")
                        .HasColumnType("date");

                    b.Property<string>("ImpactArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LinkedGlobalRiskId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinkedGlobalRiskId");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("TeamMemberRisks", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TeamNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PinnedOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId", "PinnedOrder");

                    b.ToTable("TeamNotes", (string)null);
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AzureSyncState", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.AzureConnection", "AzureConnection")
                        .WithMany()
                        .HasForeignKey("AzureConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AzureConnection");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AzureUserMapping", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany()
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AzureWorkItem", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.AzureConnection", "AzureConnection")
                        .WithMany()
                        .HasForeignKey("AzureConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AzureConnection");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.AzureWorkItemLink", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.AzureWorkItem", "AzureWorkItem")
                        .WithMany()
                        .HasForeignKey("AzureWorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany()
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AzureWorkItem");

                    b.Navigation("Project");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.GrowthFeedbackTheme", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Growth", null)
                        .WithMany("FeedbackThemes")
                        .HasForeignKey("GrowthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Domain.Entities.GrowthGoal", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Growth", null)
                        .WithMany("Goals")
                        .HasForeignKey("GrowthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Domain.Entities.GrowthGoalAction", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.GrowthGoal", null)
                        .WithMany("Actions")
                        .HasForeignKey("GrowthGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Domain.Entities.GrowthGoalCheckIn", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.GrowthGoal", null)
                        .WithMany("CheckIns")
                        .HasForeignKey("GrowthGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Domain.Entities.GrowthSkillInProgress", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Growth", "Growth")
                        .WithMany("SkillsInProgress")
                        .HasForeignKey("GrowthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Growth");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Project", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.ProductOwner", "ProductOwner")
                        .WithMany()
                        .HasForeignKey("ProductOwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Atlas.Domain.ValueObjects.ProjectCheckIn", "LatestCheckIn", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date");

                            b1.Property<string>("Note")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("LatestCheckIn");

                    b.Navigation("ProductOwner");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ProjectLinkItem", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Project", "Project")
                        .WithMany("Links")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ProjectTag", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Project", "Project")
                        .WithMany("Tags")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.ProjectTeamMember", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Project", "Project")
                        .WithMany("TeamMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("Projects")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Risk", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Project", "Project")
                        .WithMany("Risks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.RiskHistoryEntry", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Risk", null)
                        .WithMany("History")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Domain.Entities.RiskTeamMember", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Risk", "Risk")
                        .WithMany("LinkedTeamMembers")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("LinkedRisks")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Risk");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TaskDependency", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.TaskItem", "BlockerTask")
                        .WithMany()
                        .HasForeignKey("BlockerTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Atlas.Domain.Entities.TaskItem", "DependentTask")
                        .WithMany("BlockedBy")
                        .HasForeignKey("DependentTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockerTask");

                    b.Navigation("DependentTask");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Atlas.Domain.Entities.Risk", "Risk")
                        .WithMany("Tasks")
                        .HasForeignKey("RiskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TeamMember", b =>
                {
                    b.OwnsOne("Atlas.Domain.ValueObjects.TeamMemberProfile", "Profile", b1 =>
                        {
                            b1.Property<Guid>("TeamMemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("TimeZone")
                                .HasColumnType("text");

                            b1.Property<string>("TypicalHours")
                                .HasColumnType("text");

                            b1.HasKey("TeamMemberId");

                            b1.ToTable("TeamMembers");

                            b1.WithOwner()
                                .HasForeignKey("TeamMemberId");
                        });

                    b.OwnsOne("Atlas.Domain.ValueObjects.TeamMemberSignals", "Signals", b1 =>
                        {
                            b1.Property<Guid>("TeamMemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Delivery")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Load")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SupportNeeded")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TeamMemberId");

                            b1.ToTable("TeamMembers");

                            b1.WithOwner()
                                .HasForeignKey("TeamMemberId");
                        });

                    b.Navigation("Profile")
                        .IsRequired();

                    b.Navigation("Signals")
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TeamMemberRisk", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.Risk", "LinkedGlobalRisk")
                        .WithMany()
                        .HasForeignKey("LinkedGlobalRiskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Atlas.Domain.Entities.TeamMember", "TeamMember")
                        .WithMany("Risks")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedGlobalRisk");

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TeamNote", b =>
                {
                    b.HasOne("Atlas.Domain.Entities.TeamMember", null)
                        .WithMany("Notes")
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Growth", b =>
                {
                    b.Navigation("FeedbackThemes");

                    b.Navigation("Goals");

                    b.Navigation("SkillsInProgress");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.GrowthGoal", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("CheckIns");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Project", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("Risks");

                    b.Navigation("Tags");

                    b.Navigation("Tasks");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.Risk", b =>
                {
                    b.Navigation("History");

                    b.Navigation("LinkedTeamMembers");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TaskItem", b =>
                {
                    b.Navigation("BlockedBy");
                });

            modelBuilder.Entity("Atlas.Domain.Entities.TeamMember", b =>
                {
                    b.Navigation("LinkedRisks");

                    b.Navigation("Notes");

                    b.Navigation("Projects");

                    b.Navigation("Risks");
                });
#pragma warning restore 612, 618
        }
    }
}
